### ISSUE TITLE
Task list as of now

### ISSUE THREAD

**Issue by kul-riya** [kul-riya/ship-routing#2]
### Answer the following questions -
- [x] How will the factors affect algorithm?
- [x] Finalize algorithm - Djikshtra's
- [x] Finalize data structure (List or matrix), trial and error

- [x] Do we need ship specifications for indian porting?

## We need to keep this project as top priority. It is a great career boost.

**Comment by kul-riya** [comment]
- ASCAT Data Products > Daily > wind stress & wind speed+direction
- Ocean analysis daily from 2022 > 2022 > zonal current
- Ship characteristic data
